### ISSUE TITLE
no Auth Provider found for name "gcp"

### ISSUE THREAD

**Issue by vdboor** [fabmation-gmbh/helm-whatup#12]
When using kubectl with Google Cloud Platform, `helm whatup` (latest 0.3 version) doesn't work yet. Likely some go-import is missing that bundles the GCP authentication provider.

```
 ❯ helm whatup
2019/12/10 14:20:50 Error while initializing actionConfig: no Auth Provider found for name "gcp"
Error: plugin "whatup" exited with error
```

**Comment by l0nax** [comment]
Can you run whatup with the _debug_ Flag and paste the Output please?

**Comment by l0nax** [comment]
@vdboor Can you please test if the latest _develop_ Version works for you?
Because I do not have a GCP K8s-Cluster running so I can not test it.

**Comment by Serk72** [comment]
I had a very similar issue with:
```
Error while initializing actionConfig: no Auth Provider found for name "oidc"
Error: plugin "whatup" exited with error
```
and using the develop branch seems to have fixed that issue but if any of the charts I use do not exist in a helm repo I get the error:
```
Could not initialize search index: Could not find any Repo which contains {deployment name}Error: plugin "whatup" exited with error
```

**Comment by l0nax** [comment]
Thanks @Serk72 for testing it, I will soon release a new Version (_v0.3.1_).

And about your Error
> Could not initialize search index: Could not find any Repo which contains {deployment name}Error: plugin "whatup" exited with error

This is because you need an Repository which contains the Helm-Chart so `whatup` can check if there's a newer Version. If do not have a self-hosted Helm-Repository you can also use "local" Helm-Repositories.
But - if you want to - create a seperat Issue so we can discuss future details if you (eg.) need help.

**Comment by vdboor** [comment]
> @vdboor Can you please test if the latest develop Version works for you?
> Because I do not have a GCP K8s-Cluster running so I can not test it.

Yes, your change fixed the issue! :-D

FYI, my kubeconfig has the following cluster users:

```
users:
- name: my-gke-cluster
  user:
    auth-provider:
      config:
        access-token: __SKIPPED__
        cmd-args: config config-helper --format=json
        cmd-path: /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/gcloud
        expiry: "2019-12-11T11:36:18Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```

that's where the `gcp` auth provider came from.
